In [84]:
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers import AutoModelForSequenceClassification
import torch
from typing import List
import numpy as np

In [89]:
context = ["my favorite food is pasta"]
user_input = "what's your favorite?"
candidates = ["i like dancing", "i like music", "i like sandwiches", "i like to play badminton"]

In [86]:
# score: Dialog-RPT (Depth)
model_score_depth = "microsoft/DialogRPT-depth"
tokenizer_rpt_depth = AutoTokenizer.from_pretrained(model_score_depth)
model_rpt_depth = AutoModelForSequenceClassification.from_pretrained(model_score_depth)

In [91]:
model_input_rpt_depth = tokenizer_rpt_depth.batch_encode_plus(candidates, return_token_type_ids= False, return_attention_mask = False, return_tensors= "pt", return_special_tokens_mask= False, truncation=True,padding=True)

In [92]:
model_input_rpt_depth

{'input_ids': tensor([[   72,   588, 15360, 50256, 50256, 50256, 50256],
        [   72,   588,  2647, 50256, 50256, 50256, 50256],
        [   72,   588, 29777, 50256, 50256, 50256, 50256],
        [   72,   588,   284,   711,  2089,    76,  2371]])}

In [93]:
import torch

In [94]:
result = torch.Tensor(model_input_rpt_depth['input_ids'].float())

In [95]:
result

tensor([[   72.,   588., 15360., 50256., 50256., 50256., 50256.],
        [   72.,   588.,  2647., 50256., 50256., 50256., 50256.],
        [   72.,   588., 29777., 50256., 50256., 50256., 50256.],
        [   72.,   588.,   284.,   711.,  2089.,    76.,  2371.]])

In [96]:
result =res.to(torch.int64)

In [97]:
result

tensor([[   72,   588, 15360],
        [   72,   588,  2647],
        [   72,   588, 29777]])

In [98]:
new_val = model_rpt_depth(result, return_dict=True)

In [99]:
candidate_scores = torch.sigmoid(new_val.logits)

In [100]:
candidate_scores

tensor([[0.1734],
        [0.2110],
        [0.1900]], grad_fn=<SigmoidBackward>)